### PR TITLE
Add polymesh-no-modal-example

### PR DESCRIPTION
**Pull request by F-OBrien**

### CODE REVIEW

**Comment by yashovardhan** [comment]
@rtomas can you have a look at this. This also needs an update to v8.

**Comment by rtomas** [comment]
@F-OBrien the example it's working ok with v8.

can you merge to lastest changes in `main` ? 

and update the package.json to 

```
    "@web3auth/base": "^8.0.0",
    "@web3auth/base-provider": "^8.0.1",
    "@web3auth/no-modal": "^8.0.1",
    "@web3auth/openlogin-adapter": "^8.0.1",
```

**Comment by F-OBrien** [comment]
@rtomas I've rebased on `main` and updated `package.json`

**Review by rtomas — APPROVED** [review]
it's ok :)

**Pull request merged**
