### PR TITLE
Update RPC Goerli to Sepolia

### PR DESCRIPTION
**Pull request by rtomas**
Update the examples that reference Goerli to call Sepolia instead.

### CODE REVIEW

**Comment by yashovardhan** [comment]
@rtomas I see the link check is failing, can you fix that?

**Comment by rtomas** [comment]
click to update the task and now it worked. The links seem unstable. I also made a merge of a conflict

**Comment by yashovardhan** [comment]
@ihsraham please test and merge

**Review by ihsraham — APPROVED** [review]
LGTM. Covered all the examples.

**Pull request merged**
