### PR TITLE
Add comments to not being used  configuration

### PR DESCRIPTION
**Pull request by rtomas**
+ simple comment to clarify the correct configuration to use the example

### CODE REVIEW

**Comment by rtomas** [comment]
another way to fix is to change the type in this file https://github.com/Web3Auth/web3auth-web/blob/master/packages/base/src/chain/IChainInterface.ts

with this 

```
export type CustomChainConfig = {
    chainNamespace: ChainNamespaceType;
    /**
     * The chain id of the chain
     */
    chainId?: ChainNamespaceType extends "other" ? never : string; 
    /**
     * RPC target Url for the chain
     */
    rpcTarget?: ChainNamespaceType extends "other" ? never : string; 
    /**
     * web socket target Url for the chain
     */
    wsTarget?: string; 
    /**
     * Display Name for the chain
     */
    displayName?: ChainNamespaceType extends "other" ? never : string; 
    /**
     * Url of the block explorer
     */
    blockExplorer?: ChainNamespaceType extends "other" ? never : string; 
    /**
     * Default currency ticker of the network (e.g: ETH)
     */
    ticker?: ChainNamespaceType extends "other" ? never : string; 
    /**
     * Name for currency ticker (e.g: `Ethereum`)
     */
    tickerName?: ChainNamespaceType extends "other" ? never : string; 
    /**
     * Number of decimals for the currency ticker (e.g: 18)
     */
    decimals?: string; 
};


```

**Review by yashovardhan — CHANGES_REQUESTED** [review]
Actually you can remove this altogether. I don't these are mandatory fields when chain namespace is "other"


If they are still mandatory, we'll talk to the product team to get this fixed.

**Comment by rtomas** [comment]
@yashovardhan  they are mandatory
```

ERROR in src/App.tsx:30:77
TS2740: Type '{ chainNamespace: "other"; }' is missing the following properties from type 'Omit<CustomChainConfig, "chainNamespace">': chainId, rpcTarget, displayName, blockExplorer, and 2 more.
    28 |         setWeb3auth(web3authInstance);
    29 |
  > 30 |         const privateKeyProvider = new CommonPrivateKeyProvider({ config: { chainConfig } });
```

**Comment by yashovardhan** [comment]
This has been changed with v8

**Pull request closed without merging**
